modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
    issueTrackerURL="https://github.com/BlakeBr0/MoreBuckets/issues"
    modId="morebuckets"
    version="${mod_version}"
    displayName="More Buckets"
    displayURL="https://blakesmods.com/more-buckets"
    # logoFile="examplemod.png"
    authors="BlakeBr0"
    credits="thorgot"
    description='''
    Adds a bunch of new buckets.
    '''

    [[dependencies.morebuckets]]
        modId="neoforge"
        mandatory=true
        versionRange="[21.0.0-beta,)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.morebuckets]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.21,1.21.1)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.morebuckets]]
        modId="cucumber"
        mandatory=true
        versionRange="[7.0.0,)"
        ordering="NONE"
        side="BOTH"